### PR TITLE
Fix upload

### PR DESCRIPTION
**Pull request by deedee**

### CODE REVIEW

**Comment by ajefts** [comment]
@deedee @skyhit This looks better. I can use OR now.  However, the challenge status is not set to "Completed".  Are we missing the final call to set the challenge status after the phases are set to complete?

**Comment by ajefts** [comment]
Also, @deedee What controls the mock submission file name?  Thanks.

**Comment by deedee** [comment]
I'm not too familiar with OR codebase. Shouldn't it take by autopilot?So did processing payment, etc.

Mock submission file name see mockSubmissionFilePath on ContestServiceFacade.xml and mockSubmissionFileName on contest_service_facade/conf/ejb/ejb-jar.xml

**Comment by skyhit** [comment]
@deedee yes, it is my original suggestion. what if we update the challenge status?  how to do that?

**Comment by deedee** [comment]
Add these lines on closeSoftwareContest
`contest.setProjectStatus(ProjectStatus.COMPLETED);`
` projectManager.updateProject(contest, "close contest", String.valueOf(tcSubject.getUserId()));`

**Comment by ajefts** [comment]
ok @skyhit and @deedee .  I think I see why auto-pilot isn't closing the challenges.  I just confirmed on another one.  It looks like we're not setting all the required data on the submission and I think in tcs_catalog.project_result.  I'm noticing this:

1. The submission record does not have the placement or the prize_id set.
2. There is no project_results record getting generated.  I'm not sure if this happens after the review phase closes, or if autopilot does it when it closes the challenge.

**Pull request merged**
