### PR TITLE
new fileType for design

### PR DESCRIPTION
**Pull request by deedee**
#382 
database changes:
```sql
database tcs_catalog;
INSERT INTO 'informix'.file_type_lu
(file_type_id, description, sort, image_file, extension, bundled_file, create_user, create_date, modify_user, modify_date)
VALUES(47, 'Adobe Illustrator', 47, 'f', '-', 'f', 'System', CURRENT, 'System', CURRENT);
INSERT INTO 'informix'.file_type_lu
(file_type_id, description, sort, image_file, extension, bundled_file, create_user, create_date, modify_user, modify_date)
VALUES(48, 'Adobe Photoshop', 48, 'f', '-', 'f', 'System', CURRENT, 'System', CURRENT);
INSERT INTO 'informix'.file_type_lu
(file_type_id, description, sort, image_file, extension, bundled_file, create_user, create_date, modify_user, modify_date)
VALUES(49, 'Adobe XD', 49, 'f', '-', 'f', 'System', CURRENT, 'System', CURRENT);
INSERT INTO 'informix'.file_type_lu
(file_type_id, description, sort, image_file, extension, bundled_file, create_user, create_date, modify_user, modify_date)
VALUES(50, 'Sketch', 50, 'f', '-', 'f', 'System', CURRENT, 'System', CURRENT);
INSERT INTO 'informix'.file_type_lu
(file_type_id, description, sort, image_file, extension, bundled_file, create_user, create_date, modify_user, modify_date)
VALUES(51, 'Axure', 51, 'f', '-', 'f', 'System', CURRENT, 'System', CURRENT);
```
for initial setup of informix needs to change ```common_oltp:id_sequences``` of ```file_type_id_seq``` with ```next_block_start=60```

### CODE REVIEW

**Comment by skyhit** [comment]
@deedee for past challenges, will that be a problem for editing? since it is using the old list

**Comment by deedee** [comment]
@skyhit if we edit old challenge, old selected pre-defined file type will be showed as custom filetype(editable text input) with same name as before.

**Comment by skyhit** [comment]
@deedee that is cool

**Comment by deedee** [comment]
move to #411

**Comment by skyhit** [comment]
@deedee what is the problem with this?

**Comment by deedee** [comment]
nothing. I accidentally "force" push this branch - see above commit 
79a5733 , forget that there was an open PR on this.

**Pull request closed without merging**
